// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate_swagger = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/addresses": {
            "get": {
                "description": "get list of addresses",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Addresses"
                ],
                "summary": "Get Addresses",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Amount of records",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Skip to a record",
                        "name": "skip",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Find by address",
                        "name": "address",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Contract addresses only",
                        "name": "is_contract",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Token addresses only",
                        "name": "is_token",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "NFT addresses only",
                        "name": "is_nft",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Token standard, either irc2, irc3, irc31",
                        "name": "token_standard",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Field to sort by. name, balance, transaction_count, transaction_internal_count, token_transfer_count. Use leading ` + "`" + `-` + "`" + ` (ie -balance) for sort direction or omit for descending.",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.AddressList"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/addresses/contracts": {
            "get": {
                "description": "get list of contracts",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Addresses"
                ],
                "summary": "Get contracts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "contract name search",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "tokens only",
                        "name": "is_token",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "NFTs only",
                        "name": "is_nft",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "token standard, one of irc2,irc3,irc31",
                        "name": "token_standard",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "contract status, one of active, rejected, or pending",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "amount of records",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "skip to a record",
                        "name": "skip",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Field to sort by. name, balance, transaction_count, transaction_internal_count, token_transfer_count. Use leading ` + "`" + `-` + "`" + ` (ie -balance) for sort direction or omit for descending.",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ContractList"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/addresses/details/{address}": {
            "get": {
                "description": "get details of an address",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Addresses"
                ],
                "summary": "Get Address Details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "find by address",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Address"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/addresses/token-addresses/{address}": {
            "get": {
                "description": "get list of token contracts by address",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Addresses"
                ],
                "summary": "Get Token Addresses",
                "parameters": [
                    {
                        "type": "string",
                        "description": "address",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/blocks": {
            "get": {
                "description": "get historical blocks",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Blocks"
                ],
                "summary": "Get Blocks",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "amount of records",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "skip to a record",
                        "name": "skip",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "find by block number",
                        "name": "number",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "range by start block number",
                        "name": "start_number",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "range by end block number",
                        "name": "end_number",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "find by block hash",
                        "name": "hash",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "find by block creator",
                        "name": "created_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "desc or asc",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.BlockList"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/blocks/timestamp/{timestamp}": {
            "get": {
                "description": "get details of a block based on timestamp in millisecond epoch time",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Blocks"
                ],
                "summary": "Get Block Details By Nearest Timestamp",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "timestamp",
                        "name": "timestamp",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Block"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/blocks/{number}": {
            "get": {
                "description": "get details of a block",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Blocks"
                ],
                "summary": "Get Block Details",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "block number",
                        "name": "number",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Block"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/logs": {
            "get": {
                "description": "get historical logs",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Logs"
                ],
                "summary": "Get Logs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "amount of records",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "skip to a record",
                        "name": "skip",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "skip to a block",
                        "name": "block_number",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "For block range queries, a start block. Invalid with block_number",
                        "name": "block_start",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "For block range queries, an end block. Invalid with block_number",
                        "name": "block_end",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "find by transaction hash",
                        "name": "transaction_hash",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "find by address",
                        "name": "address",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "find by method",
                        "name": "method",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Log"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/stats": {
            "get": {
                "description": "get json with a summary of stats",
                "consumes": [
                    "*/*"
                ],
                "tags": [
                    "Stats"
                ],
                "summary": "Get Stats",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/stats/circulating-supply": {
            "get": {
                "description": "get circulating supply (total supply - burn wallet balance)",
                "consumes": [
                    "*/*"
                ],
                "tags": [
                    "Stats"
                ],
                "summary": "Get Stats",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "number"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/stats/market-cap": {
            "get": {
                "description": "get mkt cap (Coin Gecko Price * circulating supply)",
                "consumes": [
                    "*/*"
                ],
                "tags": [
                    "Stats"
                ],
                "summary": "Get Stats",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "number"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/stats/total-supply": {
            "get": {
                "description": "get total supply",
                "consumes": [
                    "*/*"
                ],
                "tags": [
                    "Stats"
                ],
                "summary": "Get Stats",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "number"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/transactions": {
            "get": {
                "description": "get historical transactions",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Get Transactions",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "amount of records",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "skip to a record",
                        "name": "skip",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "find by from address",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "find by to address",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "find by type",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "find by block number",
                        "name": "block_number",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "find by block number range",
                        "name": "start_block_number",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "find by block number range",
                        "name": "end_block_number",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "find by method",
                        "name": "method",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "desc or asc",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.TransactionList"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/transactions/address/{address}": {
            "get": {
                "description": "get transactions by address",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Get Transactions by address",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "amount of records",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "skip to a record",
                        "name": "skip",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "address",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.TransactionList"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/transactions/block-number/{block_number}": {
            "get": {
                "description": "get transactions by block_number",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Get Transactions by block_number",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "amount of records",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "skip to a record",
                        "name": "skip",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "block_number",
                        "name": "block_number",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.TransactionList"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/transactions/details/{hash}": {
            "get": {
                "description": "get details of a transaction",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Get Transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "transaction hash",
                        "name": "hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Transaction"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/transactions/icx/{address}": {
            "get": {
                "description": "get ICX transactions to or from an address",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Get ICX Transactions by Address",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "amount of records",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "skip to a record",
                        "name": "skip",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "address",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Transaction"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/transactions/internal/address/{address}": {
            "get": {
                "description": "Get internal transactions by address",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Get internal transactions by address",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "amount of records",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "skip to a record",
                        "name": "skip",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "find by address",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.TransactionInternalList"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/transactions/internal/block-number/{block_number}": {
            "get": {
                "description": "Get internal transactions by block number",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Get internal transactions by block number",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "amount of records",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "skip to a record",
                        "name": "skip",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "block_number",
                        "name": "block_number",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.TransactionInternalList"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/transactions/internal/{hash}": {
            "get": {
                "description": "Get internal transactions by hash",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Get internal transactions by hash",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "amount of records",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "skip to a record",
                        "name": "skip",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "find by hash",
                        "name": "hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.TransactionInternalList"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/transactions/token-holders/token-contract/{token_contract_address}": {
            "get": {
                "description": "get token holders",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Get token holders by token contract",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "amount of records",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "skip to a record",
                        "name": "skip",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "find by token contract address",
                        "name": "token_contract_address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.TokenAddress"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/transactions/token-transfers": {
            "get": {
                "description": "get historical token transfers",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Get token transfers",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "amount of records",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "skip to a record",
                        "name": "skip",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "find by from address",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "find by to address",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "find by block number",
                        "name": "block_number",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "find by block number range",
                        "name": "start_block_number",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "find by block number range",
                        "name": "end_block_number",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "find by token contract",
                        "name": "token_contract_address",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "find by transaction hash",
                        "name": "transaction_hash",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.TokenTransfer"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/transactions/token-transfers/address/{address}": {
            "get": {
                "description": "get historical token transfers by address",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Get token transfer by address",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "amount of records",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "skip to a record",
                        "name": "skip",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "find by address",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.TokenTransfer"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/transactions/token-transfers/token-contract/{token_contract_address}": {
            "get": {
                "description": "get historical token transfers by token contract",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Get token transfers by token contract",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "amount of records",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "skip to a record",
                        "name": "skip",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "find by token contract address",
                        "name": "token_contract_address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.TokenTransfer"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/metadata": {
            "get": {
                "description": "get the status of server.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Version"
                ],
                "summary": "Show the status of server.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "description": "get the status of server.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Version"
                ],
                "summary": "Show the status of server.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Address": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "audit_tx_hash": {
                    "type": "string"
                },
                "balance": {
                    "type": "number"
                },
                "code_hash": {
                    "type": "string"
                },
                "contract_type": {
                    "type": "string"
                },
                "contract_updated_block": {
                    "type": "integer"
                },
                "created_timestamp": {
                    "type": "integer"
                },
                "deploy_tx_hash": {
                    "type": "string"
                },
                "is_contract": {
                    "type": "boolean"
                },
                "is_nft": {
                    "type": "boolean"
                },
                "is_prep": {
                    "type": "boolean"
                },
                "is_token": {
                    "type": "boolean"
                },
                "log_count": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "token_standard": {
                    "type": "string"
                },
                "token_transfer_count": {
                    "type": "integer"
                },
                "transaction_count": {
                    "type": "integer"
                },
                "transaction_internal_count": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.AddressList": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "balance": {
                    "type": "number"
                },
                "is_contract": {
                    "type": "boolean"
                },
                "is_nft": {
                    "type": "boolean"
                },
                "is_token": {
                    "type": "boolean"
                },
                "token_standard": {
                    "type": "string"
                },
                "transaction_count": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.Block": {
            "type": "object",
            "properties": {
                "block_time": {
                    "type": "integer"
                },
                "failed_transaction_count": {
                    "type": "integer"
                },
                "hash": {
                    "type": "string"
                },
                "internal_transaction_amount": {
                    "type": "string"
                },
                "internal_transaction_count": {
                    "type": "integer"
                },
                "item_id": {
                    "type": "string"
                },
                "item_timestamp": {
                    "type": "string"
                },
                "merkle_root_hash": {
                    "type": "string"
                },
                "next_leader": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                },
                "parent_hash": {
                    "type": "string"
                },
                "peer_id": {
                    "type": "string"
                },
                "signature": {
                    "description": "Base",
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                },
                "transaction_amount": {
                    "type": "string"
                },
                "transaction_count": {
                    "type": "integer"
                },
                "transaction_fees": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "models.BlockList": {
            "type": "object",
            "properties": {
                "hash": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                },
                "peer_id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                },
                "transaction_amount": {
                    "type": "string"
                },
                "transaction_count": {
                    "type": "integer"
                },
                "transaction_fees": {
                    "type": "string"
                }
            }
        },
        "models.ContractList": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "balance": {
                    "type": "number"
                },
                "created_timestamp": {
                    "type": "integer"
                },
                "is_token": {
                    "type": "boolean"
                },
                "log_count": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "token_standard": {
                    "type": "string"
                },
                "transaction_count": {
                    "type": "integer"
                }
            }
        },
        "models.Log": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "block_number": {
                    "type": "integer"
                },
                "block_timestamp": {
                    "type": "integer"
                },
                "data": {
                    "type": "string"
                },
                "indexed": {
                    "type": "string"
                },
                "log_index": {
                    "type": "integer"
                },
                "method": {
                    "type": "string"
                },
                "transaction_hash": {
                    "type": "string"
                }
            }
        },
        "models.TokenAddress": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "balance": {
                    "type": "number"
                },
                "token_contract_address": {
                    "type": "string"
                },
                "token_standard": {
                    "type": "string"
                }
            }
        },
        "models.TokenTransfer": {
            "type": "object",
            "properties": {
                "block_number": {
                    "type": "integer"
                },
                "block_timestamp": {
                    "type": "integer"
                },
                "from_address": {
                    "type": "string"
                },
                "log_index": {
                    "type": "integer"
                },
                "nft_id": {
                    "type": "integer"
                },
                "to_address": {
                    "type": "string"
                },
                "token_contract_address": {
                    "type": "string"
                },
                "token_contract_name": {
                    "type": "string"
                },
                "token_contract_symbol": {
                    "type": "string"
                },
                "transaction_fee": {
                    "type": "string"
                },
                "transaction_hash": {
                    "type": "string"
                },
                "transaction_index": {
                    "type": "integer"
                },
                "value": {
                    "type": "string"
                },
                "value_decimal": {
                    "type": "number"
                }
            }
        },
        "models.Transaction": {
            "type": "object",
            "properties": {
                "block_hash": {
                    "type": "string"
                },
                "block_number": {
                    "type": "integer"
                },
                "block_timestamp": {
                    "type": "integer"
                },
                "cumulative_step_used": {
                    "type": "string"
                },
                "data": {
                    "type": "string"
                },
                "data_type": {
                    "type": "string"
                },
                "from_address": {
                    "type": "string"
                },
                "hash": {
                    "type": "string"
                },
                "log_count": {
                    "type": "integer"
                },
                "log_index": {
                    "type": "integer"
                },
                "logs_bloom": {
                    "type": "string"
                },
                "method": {
                    "type": "string"
                },
                "nid": {
                    "type": "string"
                },
                "nonce": {
                    "type": "string"
                },
                "score_address": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "step_limit": {
                    "type": "string"
                },
                "step_price": {
                    "type": "string"
                },
                "step_used": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                },
                "to_address": {
                    "type": "string"
                },
                "transaction_fee": {
                    "type": "string"
                },
                "transaction_index": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                },
                "value_decimal": {
                    "type": "number"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "models.TransactionInternalList": {
            "type": "object",
            "properties": {
                "block_hash": {
                    "type": "string"
                },
                "block_number": {
                    "type": "integer"
                },
                "block_timestamp": {
                    "type": "integer"
                },
                "data": {
                    "type": "string"
                },
                "from_address": {
                    "type": "string"
                },
                "hash": {
                    "type": "string"
                },
                "method": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "to_address": {
                    "type": "string"
                },
                "transaction_index": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "models.TransactionList": {
            "type": "object",
            "properties": {
                "block_number": {
                    "type": "integer"
                },
                "block_timestamp": {
                    "type": "integer"
                },
                "data": {
                    "type": "string"
                },
                "from_address": {
                    "type": "string"
                },
                "hash": {
                    "type": "string"
                },
                "method": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "to_address": {
                    "type": "string"
                },
                "transaction_fee": {
                    "type": "string"
                },
                "transaction_type": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                },
                "value_decimal": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo_swagger holds exported Swagger Info so clients can modify it
var SwaggerInfo_swagger = &swag.Spec{
	Version:          "2.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Icon Go API",
	Description:      "The icon tracker API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate_swagger,
}

func init() {
	swag.Register(SwaggerInfo_swagger.InstanceName(), SwaggerInfo_swagger)
}
