// Code generated by protoc-gen-go. DO NOT EDIT.
// source: address_list.proto

package models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddressList struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address"`
	TransactionCount     int64    `protobuf:"varint,2,opt,name=transaction_count,json=transactionCount,proto3" json:"transaction_count"`
	Balance              float64  `protobuf:"fixed64,3,opt,name=balance,proto3" json:"balance"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type"`
	IsContract           bool     `protobuf:"varint,5,opt,name=is_contract,json=isContract,proto3" json:"is_contract"`
	IsToken              bool     `protobuf:"varint,6,opt,name=is_token,json=isToken,proto3" json:"is_token"`
	IsNft                bool     `protobuf:"varint,7,opt,name=is_nft,json=isNft,proto3" json:"is_nft"`
	TokenStandard        string   `protobuf:"bytes,8,opt,name=token_standard,json=tokenStandard,proto3" json:"token_standard"`
}

func (m *AddressList) Reset()         { *m = AddressList{} }
func (m *AddressList) String() string { return proto.CompactTextString(m) }
func (*AddressList) ProtoMessage()    {}
func (*AddressList) Descriptor() ([]byte, []int) {
	return fileDescriptor_18eabaf48effa977, []int{0}
}

func (m *AddressList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressList.Unmarshal(m, b)
}
func (m *AddressList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressList.Marshal(b, m, deterministic)
}
func (m *AddressList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressList.Merge(m, src)
}
func (m *AddressList) XXX_Size() int {
	return xxx_messageInfo_AddressList.Size(m)
}
func (m *AddressList) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressList.DiscardUnknown(m)
}

var xxx_messageInfo_AddressList proto.InternalMessageInfo

func (m *AddressList) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *AddressList) GetTransactionCount() int64 {
	if m != nil {
		return m.TransactionCount
	}
	return 0
}

func (m *AddressList) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *AddressList) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AddressList) GetIsContract() bool {
	if m != nil {
		return m.IsContract
	}
	return false
}

func (m *AddressList) GetIsToken() bool {
	if m != nil {
		return m.IsToken
	}
	return false
}

func (m *AddressList) GetIsNft() bool {
	if m != nil {
		return m.IsNft
	}
	return false
}

func (m *AddressList) GetTokenStandard() string {
	if m != nil {
		return m.TokenStandard
	}
	return ""
}

func init() {
	proto.RegisterType((*AddressList)(nil), "models.AddressList")
}

func init() {
	proto.RegisterFile("address_list.proto", fileDescriptor_18eabaf48effa977)
}

var fileDescriptor_18eabaf48effa977 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x89, 0x6d, 0x77, 0xd7, 0x29, 0x8a, 0x0e, 0x08, 0xf1, 0xe4, 0x22, 0x08, 0x0b, 0x42,
	0x3d, 0xf8, 0x0b, 0xb4, 0x57, 0xf1, 0xb0, 0x7a, 0xf2, 0x12, 0xd2, 0x24, 0x85, 0xc1, 0x35, 0x29,
	0x99, 0xf1, 0xe0, 0x7f, 0xf7, 0x20, 0x9b, 0xee, 0x82, 0xb7, 0xbc, 0xef, 0x1b, 0x5e, 0xe0, 0x01,
	0x5a, 0xef, 0x73, 0x60, 0x36, 0x03, 0xb1, 0x6c, 0x0e, 0x39, 0x49, 0xc2, 0xea, 0x2b, 0xf9, 0x30,
	0xf0, 0xed, 0xaf, 0x82, 0xf5, 0xd3, 0x51, 0xbf, 0x10, 0x0b, 0x6a, 0xa8, 0xa7, 0x6b, 0xad, 0x5a,
	0xd5, 0x9d, 0xf6, 0x73, 0xc4, 0x7b, 0xb8, 0x94, 0x6c, 0x23, 0x5b, 0x27, 0x94, 0xa2, 0x71, 0xe9,
	0x3b, 0x8a, 0x3e, 0x69, 0x55, 0xb7, 0xe8, 0x2f, 0xfe, 0x89, 0xed, 0xc8, 0xc7, 0x9a, 0x9d, 0x1d,
	0x6c, 0x74, 0x41, 0x2f, 0x5a, 0xd5, 0xa9, 0x7e, 0x8e, 0x88, 0xb0, 0x94, 0x9f, 0x43, 0xd0, 0xcb,
	0xd2, 0x5e, 0xde, 0x78, 0x03, 0x6b, 0x62, 0xe3, 0x52, 0x94, 0x6c, 0x9d, 0xe8, 0x55, 0xab, 0xba,
	0xa6, 0x07, 0xe2, 0xed, 0x44, 0xf0, 0x1a, 0x1a, 0x62, 0x23, 0xe9, 0x33, 0x44, 0x5d, 0x15, 0x5b,
	0x13, 0xbf, 0x8f, 0x11, 0xaf, 0xa0, 0x22, 0x36, 0x71, 0x2f, 0xba, 0x2e, 0x62, 0x45, 0xfc, 0xba,
	0x17, 0xbc, 0x83, 0xf3, 0x72, 0x6e, 0x58, 0x6c, 0xf4, 0x36, 0x7b, 0xdd, 0x94, 0x0f, 0xcf, 0x0a,
	0x7d, 0x9b, 0xe0, 0x33, 0x7c, 0x34, 0x9b, 0x87, 0xe3, 0x14, 0xbb, 0xaa, 0x2c, 0xf3, 0xf8, 0x17,
	0x00, 0x00, 0xff, 0xff, 0xe4, 0x9c, 0xf0, 0x76, 0x2f, 0x01, 0x00, 0x00,
}
