// Code generated by protoc-gen-go. DO NOT EDIT.
// source: block_list.proto

package models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BlockList struct {
	TransactionCount     int64    `protobuf:"varint,1,opt,name=transaction_count,json=transactionCount,proto3" json:"transaction_count"`
	Number               int64    `protobuf:"varint,2,opt,name=number,proto3" json:"number"`
	Hash                 string   `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash"`
	Timestamp            int64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp"`
	TransactionFees      string   `protobuf:"bytes,5,opt,name=transaction_fees,json=transactionFees,proto3" json:"transaction_fees"`
	TransactionAmount    string   `protobuf:"bytes,6,opt,name=transaction_amount,json=transactionAmount,proto3" json:"transaction_amount"`
	PeerId               string   `protobuf:"bytes,7,opt,name=peer_id,json=peerId,proto3" json:"peer_id"`
}

func (m *BlockList) Reset()         { *m = BlockList{} }
func (m *BlockList) String() string { return proto.CompactTextString(m) }
func (*BlockList) ProtoMessage()    {}
func (*BlockList) Descriptor() ([]byte, []int) {
	return fileDescriptor_d846e1fe369f31a9, []int{0}
}

func (m *BlockList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockList.Unmarshal(m, b)
}
func (m *BlockList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockList.Marshal(b, m, deterministic)
}
func (m *BlockList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockList.Merge(m, src)
}
func (m *BlockList) XXX_Size() int {
	return xxx_messageInfo_BlockList.Size(m)
}
func (m *BlockList) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockList.DiscardUnknown(m)
}

var xxx_messageInfo_BlockList proto.InternalMessageInfo

func (m *BlockList) GetTransactionCount() int64 {
	if m != nil {
		return m.TransactionCount
	}
	return 0
}

func (m *BlockList) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *BlockList) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *BlockList) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *BlockList) GetTransactionFees() string {
	if m != nil {
		return m.TransactionFees
	}
	return ""
}

func (m *BlockList) GetTransactionAmount() string {
	if m != nil {
		return m.TransactionAmount
	}
	return ""
}

func (m *BlockList) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

func init() {
	proto.RegisterType((*BlockList)(nil), "models.BlockList")
}

func init() {
	proto.RegisterFile("block_list.proto", fileDescriptor_d846e1fe369f31a9)
}

var fileDescriptor_d846e1fe369f31a9 = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x15, 0x5a, 0x5c, 0x72, 0x0b, 0xe5, 0x06, 0xf0, 0xc0, 0x50, 0x31, 0x15, 0x21, 0xca,
	0xc0, 0x2f, 0xa0, 0x48, 0x48, 0x48, 0x4c, 0x1d, 0x59, 0x22, 0x27, 0x39, 0x54, 0x8b, 0xd8, 0x8e,
	0x7c, 0x97, 0x9f, 0xce, 0x8e, 0x72, 0x20, 0xd5, 0x9b, 0xdf, 0x7b, 0x9f, 0x4f, 0x4f, 0x0f, 0xd6,
	0xed, 0x90, 0xba, 0xef, 0x66, 0xf0, 0x2c, 0xbb, 0x31, 0x27, 0x49, 0x68, 0x42, 0xea, 0x69, 0xe0,
	0xbb, 0x9f, 0x0a, 0xea, 0xfd, 0x1c, 0x7e, 0x78, 0x16, 0x7c, 0x80, 0x2b, 0xc9, 0x2e, 0xb2, 0xeb,
	0xc4, 0xa7, 0xd8, 0x74, 0x69, 0x8a, 0x62, 0xab, 0x4d, 0xb5, 0x5d, 0x1c, 0xd6, 0x45, 0xf0, 0x3a,
	0xfb, 0x78, 0x0d, 0x26, 0x4e, 0xa1, 0xa5, 0x6c, 0xcf, 0x94, 0xf8, 0x57, 0x88, 0xb0, 0x3c, 0x3a,
	0x3e, 0xda, 0xc5, 0xa6, 0xda, 0xd6, 0x07, 0x7d, 0xe3, 0x2d, 0xd4, 0xe2, 0x03, 0xb1, 0xb8, 0x30,
	0xda, 0xa5, 0xe2, 0x27, 0x03, 0xef, 0xa1, 0xbc, 0xde, 0x7c, 0x11, 0xb1, 0x3d, 0xd7, 0xdf, 0x97,
	0x85, 0xff, 0x46, 0xc4, 0xf8, 0x08, 0x58, 0xa2, 0x2e, 0x68, 0x45, 0xa3, 0x70, 0xd9, 0xfd, 0x45,
	0x03, 0xbc, 0x81, 0xd5, 0x48, 0x94, 0x1b, 0xdf, 0xdb, 0x95, 0x32, 0x66, 0x96, 0xef, 0xfd, 0x1e,
	0x3e, 0x2f, 0x76, 0x4f, 0x7f, 0x1b, 0xb4, 0x46, 0x27, 0x79, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff,
	0xdf, 0x92, 0xd1, 0xce, 0x26, 0x01, 0x00, 0x00,
}
