// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contract_list.proto

package models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContractList struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address"`
	TransactionCount     int64    `protobuf:"varint,2,opt,name=transaction_count,json=transactionCount,proto3" json:"transaction_count"`
	LogCount             int64    `protobuf:"varint,3,opt,name=log_count,json=logCount,proto3" json:"log_count"`
	Balance              float64  `protobuf:"fixed64,4,opt,name=balance,proto3" json:"balance"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name"`
	Status               string   `protobuf:"bytes,6,opt,name=status,proto3" json:"status"`
	CreatedTimestamp     int64    `protobuf:"varint,7,opt,name=created_timestamp,json=createdTimestamp,proto3" json:"created_timestamp"`
	IsToken              bool     `protobuf:"varint,8,opt,name=is_token,json=isToken,proto3" json:"is_token"`
	TokenStandard        string   `protobuf:"bytes,9,opt,name=token_standard,json=tokenStandard,proto3" json:"token_standard"`
	Symbol               string   `protobuf:"bytes,10,opt,name=symbol,proto3" json:"symbol"`
}

func (m *ContractList) Reset()         { *m = ContractList{} }
func (m *ContractList) String() string { return proto.CompactTextString(m) }
func (*ContractList) ProtoMessage()    {}
func (*ContractList) Descriptor() ([]byte, []int) {
	return fileDescriptor_a94a0317b0db993e, []int{0}
}

func (m *ContractList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractList.Unmarshal(m, b)
}
func (m *ContractList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractList.Marshal(b, m, deterministic)
}
func (m *ContractList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractList.Merge(m, src)
}
func (m *ContractList) XXX_Size() int {
	return xxx_messageInfo_ContractList.Size(m)
}
func (m *ContractList) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractList.DiscardUnknown(m)
}

var xxx_messageInfo_ContractList proto.InternalMessageInfo

func (m *ContractList) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ContractList) GetTransactionCount() int64 {
	if m != nil {
		return m.TransactionCount
	}
	return 0
}

func (m *ContractList) GetLogCount() int64 {
	if m != nil {
		return m.LogCount
	}
	return 0
}

func (m *ContractList) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *ContractList) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ContractList) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ContractList) GetCreatedTimestamp() int64 {
	if m != nil {
		return m.CreatedTimestamp
	}
	return 0
}

func (m *ContractList) GetIsToken() bool {
	if m != nil {
		return m.IsToken
	}
	return false
}

func (m *ContractList) GetTokenStandard() string {
	if m != nil {
		return m.TokenStandard
	}
	return ""
}

func (m *ContractList) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func init() {
	proto.RegisterType((*ContractList)(nil), "models.ContractList")
}

func init() {
	proto.RegisterFile("contract_list.proto", fileDescriptor_a94a0317b0db993e)
}

var fileDescriptor_a94a0317b0db993e = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x49, 0x5b, 0x77, 0xb7, 0x83, 0x8a, 0x46, 0x90, 0x88, 0x97, 0x45, 0x10, 0x16, 0x84,
	0x7a, 0xf0, 0x0d, 0xec, 0xd5, 0xd3, 0xda, 0x93, 0x97, 0x65, 0x9a, 0x84, 0x12, 0xcc, 0x26, 0x25,
	0x33, 0x3d, 0xf8, 0x74, 0xbe, 0x9a, 0x34, 0x9b, 0x05, 0x6f, 0xf3, 0x7d, 0xff, 0xc0, 0xfc, 0x0c,
	0xdc, 0xe9, 0x18, 0x38, 0xa1, 0xe6, 0xc1, 0x3b, 0xe2, 0xcd, 0x31, 0x45, 0x8e, 0xb2, 0x1a, 0xa3,
	0xb1, 0x9e, 0x9e, 0x7e, 0x17, 0x70, 0xb9, 0x2d, 0xf9, 0x87, 0x23, 0x96, 0x0a, 0x6a, 0x34, 0x26,
	0x59, 0x22, 0x25, 0x5a, 0xd1, 0xad, 0xfb, 0x19, 0xe5, 0x0b, 0xdc, 0x72, 0xc2, 0x40, 0xa8, 0xd9,
	0xc5, 0x30, 0xe8, 0x78, 0x0a, 0xac, 0x16, 0xad, 0xe8, 0x96, 0xfd, 0xcd, 0xbf, 0x60, 0x7b, 0xf6,
	0xf2, 0x11, 0xd6, 0x3e, 0x1e, 0xca, 0xd2, 0x32, 0x2f, 0x35, 0x3e, 0x1e, 0xa6, 0x50, 0x41, 0xbd,
	0x47, 0x8f, 0x41, 0x5b, 0xb5, 0x6a, 0x45, 0x27, 0xfa, 0x19, 0xa5, 0x84, 0x55, 0xc0, 0xd1, 0xaa,
	0x8b, 0x7c, 0x3a, 0xcf, 0xf2, 0x1e, 0x2a, 0x62, 0xe4, 0x13, 0xa9, 0x2a, 0xdb, 0x42, 0xe7, 0x3e,
	0x3a, 0x59, 0x64, 0x6b, 0x06, 0x76, 0xa3, 0x25, 0xc6, 0xf1, 0xa8, 0xea, 0xa9, 0x4f, 0x09, 0x76,
	0xb3, 0x97, 0x0f, 0xd0, 0x38, 0x1a, 0x38, 0x7e, 0xdb, 0xa0, 0x9a, 0x56, 0x74, 0x4d, 0x5f, 0x3b,
	0xda, 0x9d, 0x51, 0x3e, 0xc3, 0x75, 0xf6, 0x03, 0x31, 0x06, 0x83, 0xc9, 0xa8, 0x75, 0xbe, 0x73,
	0x95, 0xed, 0x67, 0x91, 0xb9, 0xc6, 0xcf, 0xb8, 0x8f, 0x5e, 0x41, 0xa9, 0x91, 0xe9, 0x1d, 0xbe,
	0x9a, 0xcd, 0xeb, 0xf4, 0xcd, 0x7d, 0x95, 0x9f, 0xfb, 0xf6, 0x17, 0x00, 0x00, 0xff, 0xff, 0xf0,
	0x45, 0x7a, 0x0b, 0x73, 0x01, 0x00, 0x00,
}
