// Code generated by protoc-gen-go. DO NOT EDIT.
// source: log.proto

package models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Log struct {
	TransactionHash      string   `protobuf:"bytes,1,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash"`
	LogIndex             int64    `protobuf:"varint,2,opt,name=log_index,json=logIndex,proto3" json:"log_index"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address"`
	BlockNumber          int64    `protobuf:"varint,4,opt,name=block_number,json=blockNumber,proto3" json:"block_number"`
	Method               string   `protobuf:"bytes,5,opt,name=method,proto3" json:"method"`
	Data                 string   `protobuf:"bytes,9,opt,name=data,proto3" json:"data"`
	Indexed              string   `protobuf:"bytes,10,opt,name=indexed,proto3" json:"indexed"`
	BlockTimestamp       int64    `protobuf:"varint,11,opt,name=block_timestamp,json=blockTimestamp,proto3" json:"block_timestamp"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{0}
}

func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetTransactionHash() string {
	if m != nil {
		return m.TransactionHash
	}
	return ""
}

func (m *Log) GetLogIndex() int64 {
	if m != nil {
		return m.LogIndex
	}
	return 0
}

func (m *Log) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Log) GetBlockNumber() int64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *Log) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Log) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Log) GetIndexed() string {
	if m != nil {
		return m.Indexed
	}
	return ""
}

func (m *Log) GetBlockTimestamp() int64 {
	if m != nil {
		return m.BlockTimestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*Log)(nil), "models.Log")
}

func init() {
	proto.RegisterFile("log.proto", fileDescriptor_a153da538f858886)
}

var fileDescriptor_a153da538f858886 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x31, 0x4b, 0x03, 0x41,
	0x10, 0x85, 0x39, 0x2f, 0x9e, 0xb9, 0x89, 0x18, 0x99, 0x42, 0x06, 0x6c, 0xa2, 0x8d, 0xb1, 0x89,
	0x85, 0xff, 0xc0, 0x4a, 0x41, 0x2c, 0x82, 0x95, 0xcd, 0x31, 0x97, 0x5d, 0xee, 0x0e, 0x77, 0x77,
	0xc2, 0xee, 0x0a, 0xfe, 0x75, 0x3b, 0xc9, 0x5c, 0x0e, 0xd2, 0xed, 0xfb, 0xe0, 0xed, 0x37, 0x3c,
	0xa8, 0x9d, 0x74, 0x9b, 0x7d, 0x94, 0x2c, 0x58, 0x79, 0x31, 0xd6, 0xa5, 0xfb, 0xbf, 0x02, 0xca,
	0x77, 0xe9, 0xf0, 0x11, 0xae, 0x73, 0xe4, 0x90, 0x78, 0x97, 0x07, 0x09, 0x4d, 0xcf, 0xa9, 0xa7,
	0x62, 0x55, 0xac, 0xeb, 0xed, 0xf2, 0x84, 0xbf, 0x72, 0xea, 0xf1, 0x56, 0xff, 0x69, 0x86, 0x60,
	0xec, 0x2f, 0x9d, 0xad, 0x8a, 0x75, 0xb9, 0x9d, 0x3b, 0xe9, 0xde, 0x0e, 0x19, 0x09, 0x2e, 0xd8,
	0x98, 0x68, 0x53, 0xa2, 0x52, 0xeb, 0x53, 0xc4, 0x3b, 0xb8, 0x6c, 0x9d, 0xec, 0xbe, 0x9b, 0xf0,
	0xe3, 0x5b, 0x1b, 0x69, 0xa6, 0xcd, 0x85, 0xb2, 0x0f, 0x45, 0x78, 0x03, 0x95, 0xb7, 0xb9, 0x17,
	0x43, 0xe7, 0xda, 0x3d, 0x26, 0x44, 0x98, 0x19, 0xce, 0x4c, 0xb5, 0x52, 0x7d, 0x1f, 0x44, 0x7a,
	0x81, 0x35, 0x04, 0xa3, 0xe8, 0x18, 0xf1, 0x01, 0x96, 0xa3, 0x28, 0x0f, 0xde, 0xa6, 0xcc, 0x7e,
	0x4f, 0x0b, 0x75, 0x5d, 0x29, 0xfe, 0x9c, 0xe8, 0x0b, 0x7c, 0xcd, 0x37, 0x4f, 0xe3, 0x0e, 0x6d,
	0xa5, 0xb3, 0x3c, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0x24, 0x3f, 0x15, 0x2c, 0x23, 0x01, 0x00,
	0x00,
}
