// Code generated by protoc-gen-go. DO NOT EDIT.
// source: token_address.proto

package models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TokenAddress struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address"`
	TokenContractAddress string   `protobuf:"bytes,2,opt,name=token_contract_address,json=tokenContractAddress,proto3" json:"token_contract_address"`
	Balance              float64  `protobuf:"fixed64,3,opt,name=balance,proto3" json:"balance"`
	TokenStandard        string   `protobuf:"bytes,4,opt,name=token_standard,json=tokenStandard,proto3" json:"token_standard"`
}

func (m *TokenAddress) Reset()         { *m = TokenAddress{} }
func (m *TokenAddress) String() string { return proto.CompactTextString(m) }
func (*TokenAddress) ProtoMessage()    {}
func (*TokenAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7e686e5317797f7, []int{0}
}

func (m *TokenAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenAddress.Unmarshal(m, b)
}
func (m *TokenAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenAddress.Marshal(b, m, deterministic)
}
func (m *TokenAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenAddress.Merge(m, src)
}
func (m *TokenAddress) XXX_Size() int {
	return xxx_messageInfo_TokenAddress.Size(m)
}
func (m *TokenAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenAddress.DiscardUnknown(m)
}

var xxx_messageInfo_TokenAddress proto.InternalMessageInfo

func (m *TokenAddress) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *TokenAddress) GetTokenContractAddress() string {
	if m != nil {
		return m.TokenContractAddress
	}
	return ""
}

func (m *TokenAddress) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *TokenAddress) GetTokenStandard() string {
	if m != nil {
		return m.TokenStandard
	}
	return ""
}

func init() {
	proto.RegisterType((*TokenAddress)(nil), "models.TokenAddress")
}

func init() {
	proto.RegisterFile("token_address.proto", fileDescriptor_b7e686e5317797f7)
}

var fileDescriptor_b7e686e5317797f7 = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0xc9, 0xcf, 0x4e,
	0xcd, 0x8b, 0x4f, 0x4c, 0x49, 0x29, 0x4a, 0x2d, 0x2e, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0xcb, 0xcd, 0x4f, 0x49, 0xcd, 0x29, 0x56, 0x9a, 0xcf, 0xc8, 0xc5, 0x13, 0x02, 0x92, 0x77,
	0x84, 0x48, 0x0b, 0x49, 0x70, 0xb1, 0x43, 0x55, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xc1,
	0xb8, 0x42, 0x26, 0x5c, 0x62, 0x10, 0x93, 0x92, 0xf3, 0xf3, 0x4a, 0x8a, 0x12, 0x93, 0x4b, 0x60,
	0x46, 0x4a, 0x30, 0x81, 0x15, 0x8a, 0x80, 0x65, 0x9d, 0xa1, 0x92, 0x48, 0xe6, 0x25, 0x25, 0xe6,
	0x24, 0xe6, 0x25, 0xa7, 0x4a, 0x30, 0x2b, 0x30, 0x6a, 0x30, 0x06, 0xc1, 0xb8, 0x42, 0xaa, 0x5c,
	0x7c, 0x10, 0xf3, 0x8a, 0x4b, 0x12, 0xf3, 0x52, 0x12, 0x8b, 0x52, 0x24, 0x58, 0xc0, 0xe6, 0xf0,
	0x82, 0x45, 0x83, 0xa1, 0x82, 0x4e, 0x5c, 0x51, 0x1c, 0x7a, 0xfa, 0x10, 0xd7, 0x26, 0xb1, 0x81,
	0x1d, 0x6f, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xfa, 0xf3, 0x20, 0x28, 0xd3, 0x00, 0x00, 0x00,
}
