// Code generated by protoc-gen-go. DO NOT EDIT.
// source: token_transfer.proto

package models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TokenTransfer struct {
	TokenContractAddress string   `protobuf:"bytes,1,opt,name=token_contract_address,json=tokenContractAddress,proto3" json:"token_contract_address"`
	FromAddress          string   `protobuf:"bytes,2,opt,name=from_address,json=fromAddress,proto3" json:"from_address"`
	ToAddress            string   `protobuf:"bytes,3,opt,name=to_address,json=toAddress,proto3" json:"to_address"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value"`
	TransactionHash      string   `protobuf:"bytes,5,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash"`
	LogIndex             int64    `protobuf:"varint,6,opt,name=log_index,json=logIndex,proto3" json:"log_index"`
	BlockNumber          int64    `protobuf:"varint,7,opt,name=block_number,json=blockNumber,proto3" json:"block_number"`
	ValueDecimal         float64  `protobuf:"fixed64,8,opt,name=value_decimal,json=valueDecimal,proto3" json:"value_decimal"`
	BlockTimestamp       int64    `protobuf:"varint,9,opt,name=block_timestamp,json=blockTimestamp,proto3" json:"block_timestamp"`
	TokenContractName    string   `protobuf:"bytes,10,opt,name=token_contract_name,json=tokenContractName,proto3" json:"token_contract_name"`
	TransactionFee       string   `protobuf:"bytes,11,opt,name=transaction_fee,json=transactionFee,proto3" json:"transaction_fee"`
	TokenContractSymbol  string   `protobuf:"bytes,12,opt,name=token_contract_symbol,json=tokenContractSymbol,proto3" json:"token_contract_symbol"`
}

func (m *TokenTransfer) Reset()         { *m = TokenTransfer{} }
func (m *TokenTransfer) String() string { return proto.CompactTextString(m) }
func (*TokenTransfer) ProtoMessage()    {}
func (*TokenTransfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dee5df8e2b2416f, []int{0}
}

func (m *TokenTransfer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenTransfer.Unmarshal(m, b)
}
func (m *TokenTransfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenTransfer.Marshal(b, m, deterministic)
}
func (m *TokenTransfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenTransfer.Merge(m, src)
}
func (m *TokenTransfer) XXX_Size() int {
	return xxx_messageInfo_TokenTransfer.Size(m)
}
func (m *TokenTransfer) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenTransfer.DiscardUnknown(m)
}

var xxx_messageInfo_TokenTransfer proto.InternalMessageInfo

func (m *TokenTransfer) GetTokenContractAddress() string {
	if m != nil {
		return m.TokenContractAddress
	}
	return ""
}

func (m *TokenTransfer) GetFromAddress() string {
	if m != nil {
		return m.FromAddress
	}
	return ""
}

func (m *TokenTransfer) GetToAddress() string {
	if m != nil {
		return m.ToAddress
	}
	return ""
}

func (m *TokenTransfer) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *TokenTransfer) GetTransactionHash() string {
	if m != nil {
		return m.TransactionHash
	}
	return ""
}

func (m *TokenTransfer) GetLogIndex() int64 {
	if m != nil {
		return m.LogIndex
	}
	return 0
}

func (m *TokenTransfer) GetBlockNumber() int64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *TokenTransfer) GetValueDecimal() float64 {
	if m != nil {
		return m.ValueDecimal
	}
	return 0
}

func (m *TokenTransfer) GetBlockTimestamp() int64 {
	if m != nil {
		return m.BlockTimestamp
	}
	return 0
}

func (m *TokenTransfer) GetTokenContractName() string {
	if m != nil {
		return m.TokenContractName
	}
	return ""
}

func (m *TokenTransfer) GetTransactionFee() string {
	if m != nil {
		return m.TransactionFee
	}
	return ""
}

func (m *TokenTransfer) GetTokenContractSymbol() string {
	if m != nil {
		return m.TokenContractSymbol
	}
	return ""
}

func init() {
	proto.RegisterType((*TokenTransfer)(nil), "models.TokenTransfer")
}

func init() {
	proto.RegisterFile("token_transfer.proto", fileDescriptor_4dee5df8e2b2416f)
}

var fileDescriptor_4dee5df8e2b2416f = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0x4d, 0x4f, 0xea, 0x40,
	0x14, 0x86, 0xd3, 0xcb, 0x85, 0x4b, 0x0f, 0x5f, 0xd7, 0x01, 0xcd, 0x24, 0xc6, 0x04, 0x75, 0x21,
	0x6e, 0x30, 0x51, 0xff, 0x80, 0x1f, 0x31, 0xba, 0x61, 0x81, 0xac, 0xdc, 0x34, 0xd3, 0xf6, 0x00,
	0x0d, 0xf3, 0x41, 0x66, 0x06, 0xa3, 0xbf, 0xd7, 0x3f, 0x62, 0x7a, 0x06, 0x08, 0xb0, 0x9c, 0xe7,
	0x7d, 0xfa, 0xf6, 0xf4, 0x74, 0xa0, 0xe7, 0xcd, 0x02, 0x75, 0xe2, 0xad, 0xd0, 0x6e, 0x8a, 0x76,
	0xb8, 0xb4, 0xc6, 0x1b, 0x56, 0x53, 0x26, 0x47, 0xe9, 0x2e, 0x7e, 0x2a, 0xd0, 0x9a, 0x94, 0xc2,
	0x64, 0x9d, 0xb3, 0x7b, 0x38, 0x09, 0x4f, 0x64, 0x46, 0x7b, 0x2b, 0x32, 0x9f, 0x88, 0x3c, 0xb7,
	0xe8, 0x1c, 0x8f, 0xfa, 0xd1, 0x20, 0x1e, 0x87, 0xbe, 0xa7, 0x75, 0xf8, 0x10, 0x32, 0x76, 0x0e,
	0xcd, 0xa9, 0x35, 0x6a, 0xeb, 0xfe, 0x21, 0xb7, 0x51, 0xb2, 0x8d, 0x72, 0x06, 0xe0, 0xcd, 0x56,
	0xa8, 0x90, 0x10, 0x7b, 0xb3, 0x89, 0x7b, 0x50, 0xfd, 0x14, 0x72, 0x85, 0xfc, 0x2f, 0x25, 0xe1,
	0xc0, 0xae, 0xe1, 0x3f, 0x4d, 0x2e, 0x32, 0x5f, 0x18, 0x9d, 0xcc, 0x85, 0x9b, 0xf3, 0x2a, 0x09,
	0x9d, 0x1d, 0xfe, 0x2a, 0xdc, 0x9c, 0x9d, 0x42, 0x2c, 0xcd, 0x2c, 0x29, 0x74, 0x8e, 0x5f, 0xbc,
	0xd6, 0x8f, 0x06, 0x95, 0x71, 0x5d, 0x9a, 0xd9, 0x5b, 0x79, 0x2e, 0xe7, 0x4b, 0xa5, 0xc9, 0x16,
	0x89, 0x5e, 0xa9, 0x14, 0x2d, 0xff, 0x47, 0x79, 0x83, 0xd8, 0x88, 0x10, 0xbb, 0x84, 0x16, 0xbd,
	0x33, 0xc9, 0x31, 0x2b, 0x94, 0x90, 0xbc, 0xde, 0x8f, 0x06, 0xd1, 0xb8, 0x49, 0xf0, 0x39, 0x30,
	0x76, 0x05, 0x9d, 0xd0, 0xe3, 0x0b, 0x85, 0xce, 0x0b, 0xb5, 0xe4, 0x31, 0x55, 0xb5, 0x09, 0x4f,
	0x36, 0x94, 0x0d, 0xa1, 0x7b, 0xb0, 0x46, 0x2d, 0x14, 0x72, 0xa0, 0xd9, 0x8f, 0xf6, 0x76, 0x38,
	0x12, 0x0a, 0xcb, 0xe2, 0xdd, 0x0f, 0x9d, 0x22, 0xf2, 0x06, 0xb9, 0xed, 0x1d, 0xfc, 0x82, 0xc8,
	0x6e, 0xe1, 0xf8, 0xa0, 0xd8, 0x7d, 0xab, 0xd4, 0x48, 0xde, 0x24, 0xbd, 0xbb, 0x57, 0xfd, 0x4e,
	0xd1, 0x23, 0x7c, 0xd4, 0x87, 0x37, 0xe1, 0x8f, 0xa7, 0x35, 0xba, 0x00, 0x77, 0xbf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x9a, 0xd9, 0xce, 0x72, 0x18, 0x02, 0x00, 0x00,
}
