// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction_list.proto

package models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransactionList struct {
	FromAddress          string   `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"from_address"`
	ToAddress            string   `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"to_address"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value"`
	BlockTimestamp       int64    `protobuf:"varint,4,opt,name=block_timestamp,json=blockTimestamp,proto3" json:"block_timestamp"`
	Hash                 string   `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash"`
	BlockNumber          int64    `protobuf:"varint,6,opt,name=block_number,json=blockNumber,proto3" json:"block_number"`
	TransactionFee       string   `protobuf:"bytes,7,opt,name=transaction_fee,json=transactionFee,proto3" json:"transaction_fee"`
	Status               string   `protobuf:"bytes,8,opt,name=status,proto3" json:"status"`
	Type                 string   `protobuf:"bytes,9,opt,name=type,proto3" json:"type"`
	Method               string   `protobuf:"bytes,10,opt,name=method,proto3" json:"method"`
	ValueDecimal         float64  `protobuf:"fixed64,11,opt,name=value_decimal,json=valueDecimal,proto3" json:"value_decimal"`
	Data                 string   `protobuf:"bytes,12,opt,name=data,proto3" json:"data"`
	TransactionType      int32    `protobuf:"varint,13,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type"`
}

func (m *TransactionList) Reset()         { *m = TransactionList{} }
func (m *TransactionList) String() string { return proto.CompactTextString(m) }
func (*TransactionList) ProtoMessage()    {}
func (*TransactionList) Descriptor() ([]byte, []int) {
	return fileDescriptor_396544a4d5fcb28a, []int{0}
}

func (m *TransactionList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionList.Unmarshal(m, b)
}
func (m *TransactionList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionList.Marshal(b, m, deterministic)
}
func (m *TransactionList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionList.Merge(m, src)
}
func (m *TransactionList) XXX_Size() int {
	return xxx_messageInfo_TransactionList.Size(m)
}
func (m *TransactionList) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionList.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionList proto.InternalMessageInfo

func (m *TransactionList) GetFromAddress() string {
	if m != nil {
		return m.FromAddress
	}
	return ""
}

func (m *TransactionList) GetToAddress() string {
	if m != nil {
		return m.ToAddress
	}
	return ""
}

func (m *TransactionList) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *TransactionList) GetBlockTimestamp() int64 {
	if m != nil {
		return m.BlockTimestamp
	}
	return 0
}

func (m *TransactionList) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *TransactionList) GetBlockNumber() int64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *TransactionList) GetTransactionFee() string {
	if m != nil {
		return m.TransactionFee
	}
	return ""
}

func (m *TransactionList) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TransactionList) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TransactionList) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *TransactionList) GetValueDecimal() float64 {
	if m != nil {
		return m.ValueDecimal
	}
	return 0
}

func (m *TransactionList) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *TransactionList) GetTransactionType() int32 {
	if m != nil {
		return m.TransactionType
	}
	return 0
}

func init() {
	proto.RegisterType((*TransactionList)(nil), "models.TransactionList")
}

func init() {
	proto.RegisterFile("transaction_list.proto", fileDescriptor_396544a4d5fcb28a)
}

var fileDescriptor_396544a4d5fcb28a = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xcf, 0x4e, 0xc3, 0x30,
	0x0c, 0xc6, 0x15, 0xb6, 0x95, 0xcd, 0xfb, 0x87, 0x22, 0x34, 0xe5, 0x82, 0x54, 0xe0, 0x40, 0xb9,
	0x8c, 0x03, 0x4f, 0x00, 0x42, 0x9c, 0x10, 0x87, 0x6a, 0x27, 0x2e, 0x55, 0xb6, 0x78, 0x5a, 0x45,
	0xd3, 0x54, 0x8d, 0x8b, 0xb4, 0x57, 0xe1, 0x69, 0x51, 0x1c, 0x06, 0xbd, 0xd9, 0x3f, 0x7f, 0xfe,
	0x6c, 0xcb, 0xb0, 0xa2, 0x56, 0xd7, 0x5e, 0xef, 0xa8, 0x74, 0x75, 0x51, 0x95, 0x9e, 0xd6, 0x4d,
	0xeb, 0xc8, 0xc9, 0xc4, 0x3a, 0x83, 0x95, 0xbf, 0xf9, 0x1e, 0xc0, 0x72, 0xf3, 0x2f, 0x79, 0x2b,
	0x3d, 0xc9, 0x6b, 0x98, 0xed, 0x5b, 0x67, 0x0b, 0x6d, 0x4c, 0x8b, 0xde, 0x2b, 0x91, 0x8a, 0x6c,
	0x92, 0x4f, 0x03, 0x7b, 0x8a, 0x48, 0x5e, 0x01, 0x90, 0xfb, 0x13, 0x9c, 0xb1, 0x60, 0x42, 0xee,
	0x54, 0xbe, 0x84, 0xd1, 0x97, 0xae, 0x3a, 0x54, 0x03, 0xae, 0xc4, 0x44, 0xde, 0xc1, 0x72, 0x5b,
	0xb9, 0xdd, 0x67, 0x41, 0xa5, 0x45, 0x4f, 0xda, 0x36, 0x6a, 0x98, 0x8a, 0x6c, 0x90, 0x2f, 0x18,
	0x6f, 0x4e, 0x54, 0x4a, 0x18, 0x1e, 0xb4, 0x3f, 0xa8, 0x11, 0x77, 0x73, 0x1c, 0x96, 0x8a, 0xcd,
	0x75, 0x67, 0xb7, 0xd8, 0xaa, 0x84, 0x3b, 0xa7, 0xcc, 0xde, 0x19, 0x05, 0xff, 0xfe, 0xb5, 0x7b,
	0x44, 0x75, 0xce, 0x0e, 0x8b, 0x1e, 0x7e, 0x45, 0x94, 0x2b, 0x48, 0x3c, 0x69, 0xea, 0xbc, 0x1a,
	0x73, 0xfd, 0x37, 0x0b, 0x73, 0xe9, 0xd8, 0xa0, 0x9a, 0xc4, 0xb9, 0x21, 0x0e, 0x5a, 0x8b, 0x74,
	0x70, 0x46, 0x41, 0xd4, 0xc6, 0x4c, 0xde, 0xc2, 0x9c, 0xaf, 0x2a, 0x0c, 0xee, 0x4a, 0xab, 0x2b,
	0x35, 0x4d, 0x45, 0x26, 0xf2, 0x19, 0xc3, 0x97, 0xc8, 0x82, 0xa1, 0xd1, 0xa4, 0xd5, 0x2c, 0x1a,
	0x86, 0x58, 0xde, 0xc3, 0x45, 0x7f, 0x4b, 0x1e, 0x38, 0x4f, 0x45, 0x36, 0xca, 0xfb, 0xdb, 0x6f,
	0x8e, 0x0d, 0x3e, 0xc3, 0xc7, 0x78, 0xfd, 0x10, 0x1f, 0xb5, 0x4d, 0xf8, 0x6f, 0x8f, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x5a, 0x49, 0x3a, 0xbe, 0xd1, 0x01, 0x00, 0x00,
}
