// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction_internal_list.proto

package models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransactionInternalList struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type"`
	FromAddress          string   `protobuf:"bytes,2,opt,name=from_address,json=fromAddress,proto3" json:"from_address"`
	ToAddress            string   `protobuf:"bytes,3,opt,name=to_address,json=toAddress,proto3" json:"to_address"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value"`
	BlockTimestamp       int64    `protobuf:"varint,5,opt,name=block_timestamp,json=blockTimestamp,proto3" json:"block_timestamp"`
	Hash                 string   `protobuf:"bytes,6,opt,name=hash,proto3" json:"hash"`
	TransactionIndex     int64    `protobuf:"varint,7,opt,name=transaction_index,json=transactionIndex,proto3" json:"transaction_index"`
	BlockHash            string   `protobuf:"bytes,8,opt,name=block_hash,json=blockHash,proto3" json:"block_hash"`
	BlockNumber          int64    `protobuf:"varint,9,opt,name=block_number,json=blockNumber,proto3" json:"block_number"`
	Data                 string   `protobuf:"bytes,10,opt,name=data,proto3" json:"data"`
	Status               string   `protobuf:"bytes,11,opt,name=status,proto3" json:"status"`
}

func (m *TransactionInternalList) Reset()         { *m = TransactionInternalList{} }
func (m *TransactionInternalList) String() string { return proto.CompactTextString(m) }
func (*TransactionInternalList) ProtoMessage()    {}
func (*TransactionInternalList) Descriptor() ([]byte, []int) {
	return fileDescriptor_0992daefc01aec96, []int{0}
}

func (m *TransactionInternalList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionInternalList.Unmarshal(m, b)
}
func (m *TransactionInternalList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionInternalList.Marshal(b, m, deterministic)
}
func (m *TransactionInternalList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionInternalList.Merge(m, src)
}
func (m *TransactionInternalList) XXX_Size() int {
	return xxx_messageInfo_TransactionInternalList.Size(m)
}
func (m *TransactionInternalList) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionInternalList.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionInternalList proto.InternalMessageInfo

func (m *TransactionInternalList) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TransactionInternalList) GetFromAddress() string {
	if m != nil {
		return m.FromAddress
	}
	return ""
}

func (m *TransactionInternalList) GetToAddress() string {
	if m != nil {
		return m.ToAddress
	}
	return ""
}

func (m *TransactionInternalList) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *TransactionInternalList) GetBlockTimestamp() int64 {
	if m != nil {
		return m.BlockTimestamp
	}
	return 0
}

func (m *TransactionInternalList) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *TransactionInternalList) GetTransactionIndex() int64 {
	if m != nil {
		return m.TransactionIndex
	}
	return 0
}

func (m *TransactionInternalList) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *TransactionInternalList) GetBlockNumber() int64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *TransactionInternalList) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *TransactionInternalList) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*TransactionInternalList)(nil), "models.TransactionInternalList")
}

func init() {
	proto.RegisterFile("transaction_internal_list.proto", fileDescriptor_0992daefc01aec96)
}

var fileDescriptor_0992daefc01aec96 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x4d, 0x4f, 0xc3, 0x30,
	0x0c, 0x86, 0xb5, 0xaf, 0xb2, 0xba, 0x13, 0x1f, 0x11, 0x82, 0x5c, 0x10, 0x1b, 0x17, 0x26, 0x21,
	0x8d, 0x03, 0xbf, 0x00, 0x4e, 0x20, 0x21, 0x0e, 0xd3, 0x4e, 0x5c, 0x2a, 0x77, 0x09, 0x5a, 0x45,
	0xdb, 0x54, 0xb1, 0x8b, 0xc6, 0x8f, 0xe5, 0xbf, 0xa0, 0x38, 0x1b, 0x1f, 0x37, 0xfb, 0x79, 0xdf,
	0x38, 0xaf, 0x0d, 0x97, 0xec, 0xb1, 0x21, 0x5c, 0x73, 0xe9, 0x9a, 0xbc, 0x6c, 0xd8, 0xfa, 0x06,
	0xab, 0xbc, 0x2a, 0x89, 0x17, 0xad, 0x77, 0xec, 0x54, 0x52, 0x3b, 0x63, 0x2b, 0xba, 0xfa, 0xea,
	0xc3, 0xf9, 0xea, 0xd7, 0xfb, 0xb4, 0xb3, 0x3e, 0x97, 0xc4, 0x4a, 0xc1, 0x90, 0x3f, 0x5b, 0xab,
	0x7b, 0xd3, 0xde, 0x3c, 0x5d, 0x4a, 0xad, 0x66, 0x30, 0x79, 0xf3, 0xae, 0xce, 0xd1, 0x18, 0x6f,
	0x89, 0x74, 0x5f, 0xb4, 0x2c, 0xb0, 0xfb, 0x88, 0xd4, 0x05, 0x00, 0xbb, 0x1f, 0xc3, 0x40, 0x0c,
	0x29, 0xbb, 0xbd, 0x7c, 0x0a, 0xa3, 0x0f, 0xac, 0x3a, 0xab, 0x87, 0xa2, 0xc4, 0x46, 0x5d, 0xc3,
	0x51, 0x51, 0xb9, 0xf5, 0x7b, 0xce, 0x65, 0x6d, 0x89, 0xb1, 0x6e, 0xf5, 0x68, 0xda, 0x9b, 0x0f,
	0x96, 0x87, 0x82, 0x57, 0x7b, 0x1a, 0x42, 0x6d, 0x90, 0x36, 0x3a, 0x89, 0xa1, 0x42, 0xad, 0x6e,
	0xe0, 0xe4, 0xff, 0xbe, 0xc6, 0x6e, 0xf5, 0x81, 0x3c, 0x3f, 0xe6, 0xbf, 0xcb, 0x19, 0xbb, 0x0d,
	0xf1, 0xe2, 0x4f, 0x32, 0x66, 0x1c, 0xe3, 0x09, 0x79, 0x0c, 0xb3, 0x66, 0x30, 0x89, 0x72, 0xd3,
	0xd5, 0x85, 0xf5, 0x3a, 0x95, 0x31, 0x99, 0xb0, 0x17, 0x41, 0x21, 0x82, 0x41, 0x46, 0x0d, 0x31,
	0x42, 0xa8, 0xd5, 0x19, 0x24, 0xc4, 0xc8, 0x1d, 0xe9, 0x4c, 0xe8, 0xae, 0x7b, 0x80, 0xd7, 0xf1,
	0xe2, 0x36, 0xde, 0xba, 0x48, 0xe4, 0xf4, 0x77, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf6, 0xd0,
	0x33, 0xd7, 0x9d, 0x01, 0x00, 0x00,
}
