// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

package models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Transaction struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash"`
	LogIndex             int64    `protobuf:"varint,2,opt,name=log_index,json=logIndex,proto3" json:"log_index"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type"`
	Method               string   `protobuf:"bytes,4,opt,name=method,proto3" json:"method"`
	FromAddress          string   `protobuf:"bytes,5,opt,name=from_address,json=fromAddress,proto3" json:"from_address"`
	ToAddress            string   `protobuf:"bytes,6,opt,name=to_address,json=toAddress,proto3" json:"to_address"`
	BlockNumber          int64    `protobuf:"varint,7,opt,name=block_number,json=blockNumber,proto3" json:"block_number"`
	LogCount             int64    `protobuf:"varint,8,opt,name=log_count,json=logCount,proto3" json:"log_count"`
	Version              string   `protobuf:"bytes,9,opt,name=version,proto3" json:"version"`
	Value                string   `protobuf:"bytes,10,opt,name=value,proto3" json:"value"`
	ValueDecimal         float64  `protobuf:"fixed64,11,opt,name=value_decimal,json=valueDecimal,proto3" json:"value_decimal"`
	StepLimit            string   `protobuf:"bytes,12,opt,name=step_limit,json=stepLimit,proto3" json:"step_limit"`
	Timestamp            int64    `protobuf:"varint,13,opt,name=timestamp,proto3" json:"timestamp"`
	BlockTimestamp       int64    `protobuf:"varint,14,opt,name=block_timestamp,json=blockTimestamp,proto3" json:"block_timestamp"`
	Nid                  string   `protobuf:"bytes,15,opt,name=nid,proto3" json:"nid"`
	Nonce                string   `protobuf:"bytes,16,opt,name=nonce,proto3" json:"nonce"`
	TransactionIndex     int64    `protobuf:"varint,17,opt,name=transaction_index,json=transactionIndex,proto3" json:"transaction_index"`
	BlockHash            string   `protobuf:"bytes,18,opt,name=block_hash,json=blockHash,proto3" json:"block_hash"`
	TransactionFee       string   `protobuf:"bytes,19,opt,name=transaction_fee,json=transactionFee,proto3" json:"transaction_fee"`
	Signature            string   `protobuf:"bytes,20,opt,name=signature,proto3" json:"signature"`
	DataType             string   `protobuf:"bytes,21,opt,name=data_type,json=dataType,proto3" json:"data_type"`
	Data                 string   `protobuf:"bytes,22,opt,name=data,proto3" json:"data"`
	CumulativeStepUsed   string   `protobuf:"bytes,23,opt,name=cumulative_step_used,json=cumulativeStepUsed,proto3" json:"cumulative_step_used"`
	StepUsed             string   `protobuf:"bytes,24,opt,name=step_used,json=stepUsed,proto3" json:"step_used"`
	StepPrice            string   `protobuf:"bytes,25,opt,name=step_price,json=stepPrice,proto3" json:"step_price"`
	ScoreAddress         string   `protobuf:"bytes,26,opt,name=score_address,json=scoreAddress,proto3" json:"score_address"`
	LogsBloom            string   `protobuf:"bytes,27,opt,name=logs_bloom,json=logsBloom,proto3" json:"logs_bloom"`
	Status               string   `protobuf:"bytes,28,opt,name=status,proto3" json:"status"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{0}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Transaction) GetLogIndex() int64 {
	if m != nil {
		return m.LogIndex
	}
	return 0
}

func (m *Transaction) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Transaction) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Transaction) GetFromAddress() string {
	if m != nil {
		return m.FromAddress
	}
	return ""
}

func (m *Transaction) GetToAddress() string {
	if m != nil {
		return m.ToAddress
	}
	return ""
}

func (m *Transaction) GetBlockNumber() int64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *Transaction) GetLogCount() int64 {
	if m != nil {
		return m.LogCount
	}
	return 0
}

func (m *Transaction) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Transaction) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Transaction) GetValueDecimal() float64 {
	if m != nil {
		return m.ValueDecimal
	}
	return 0
}

func (m *Transaction) GetStepLimit() string {
	if m != nil {
		return m.StepLimit
	}
	return ""
}

func (m *Transaction) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Transaction) GetBlockTimestamp() int64 {
	if m != nil {
		return m.BlockTimestamp
	}
	return 0
}

func (m *Transaction) GetNid() string {
	if m != nil {
		return m.Nid
	}
	return ""
}

func (m *Transaction) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *Transaction) GetTransactionIndex() int64 {
	if m != nil {
		return m.TransactionIndex
	}
	return 0
}

func (m *Transaction) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *Transaction) GetTransactionFee() string {
	if m != nil {
		return m.TransactionFee
	}
	return ""
}

func (m *Transaction) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *Transaction) GetDataType() string {
	if m != nil {
		return m.DataType
	}
	return ""
}

func (m *Transaction) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Transaction) GetCumulativeStepUsed() string {
	if m != nil {
		return m.CumulativeStepUsed
	}
	return ""
}

func (m *Transaction) GetStepUsed() string {
	if m != nil {
		return m.StepUsed
	}
	return ""
}

func (m *Transaction) GetStepPrice() string {
	if m != nil {
		return m.StepPrice
	}
	return ""
}

func (m *Transaction) GetScoreAddress() string {
	if m != nil {
		return m.ScoreAddress
	}
	return ""
}

func (m *Transaction) GetLogsBloom() string {
	if m != nil {
		return m.LogsBloom
	}
	return ""
}

func (m *Transaction) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*Transaction)(nil), "models.Transaction")
}

func init() {
	proto.RegisterFile("transaction.proto", fileDescriptor_2cc4e03d2c28c490)
}

var fileDescriptor_2cc4e03d2c28c490 = []byte{
	// 503 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x15, 0x92, 0xa6, 0xc9, 0xc4, 0x4d, 0xd2, 0x25, 0x94, 0x81, 0xb6, 0x52, 0x0a, 0x87,
	0x46, 0x42, 0x2a, 0x48, 0x3c, 0x01, 0x05, 0x21, 0x90, 0x10, 0x42, 0x21, 0x5c, 0xb8, 0x58, 0x1b,
	0x7b, 0x9a, 0xac, 0xb0, 0xbd, 0x96, 0x77, 0x1d, 0xc1, 0xc3, 0xf2, 0x2e, 0x68, 0x66, 0xe3, 0x38,
	0xdc, 0x66, 0xbe, 0xf9, 0xbd, 0xfb, 0xdb, 0xff, 0x18, 0xce, 0x7d, 0xa5, 0x0b, 0xa7, 0x13, 0x6f,
	0x6c, 0x71, 0x57, 0x56, 0xd6, 0x5b, 0xd5, 0xcf, 0x6d, 0x4a, 0x99, 0x7b, 0xf1, 0xb7, 0x0f, 0xa3,
	0x55, 0x3b, 0x55, 0x0a, 0x7a, 0x5b, 0xed, 0xb6, 0xd8, 0x99, 0x77, 0x16, 0xc3, 0xa5, 0xd4, 0xea,
	0x12, 0x86, 0x99, 0xdd, 0xc4, 0xa6, 0x48, 0xe9, 0x37, 0x3e, 0x9a, 0x77, 0x16, 0xdd, 0xe5, 0x20,
	0xb3, 0x9b, 0xcf, 0xdc, 0xf3, 0x03, 0xfe, 0x4f, 0x49, 0xd8, 0x0d, 0x0f, 0x70, 0xad, 0x2e, 0xa0,
	0x9f, 0x93, 0xdf, 0xda, 0x14, 0x7b, 0x42, 0xf7, 0x9d, 0xba, 0x81, 0xe8, 0xa1, 0xb2, 0x79, 0xac,
	0xd3, 0xb4, 0x22, 0xe7, 0xf0, 0x44, 0xa6, 0x23, 0x66, 0xef, 0x02, 0x52, 0xd7, 0x00, 0xde, 0x1e,
	0x04, 0x7d, 0x11, 0x0c, 0xbd, 0x6d, 0xc6, 0x37, 0x10, 0xad, 0x33, 0x9b, 0xfc, 0x8a, 0x8b, 0x3a,
	0x5f, 0x53, 0x85, 0xa7, 0xe2, 0x66, 0x24, 0xec, 0xab, 0xa0, 0xc6, 0x6d, 0x62, 0xeb, 0xc2, 0xe3,
	0xe0, 0xe0, 0xf6, 0x3d, 0xf7, 0x0a, 0xe1, 0x74, 0x47, 0x95, 0x33, 0xb6, 0xc0, 0xa1, 0x9c, 0xdd,
	0xb4, 0x6a, 0x06, 0x27, 0x3b, 0x9d, 0xd5, 0x84, 0x20, 0x3c, 0x34, 0xea, 0x25, 0x9c, 0x49, 0x11,
	0xa7, 0x94, 0x98, 0x5c, 0x67, 0x38, 0x9a, 0x77, 0x16, 0x9d, 0x65, 0x24, 0xf0, 0x43, 0x60, 0xec,
	0xd9, 0x79, 0x2a, 0xe3, 0xcc, 0xe4, 0xc6, 0x63, 0x14, 0x3c, 0x33, 0xf9, 0xc2, 0x40, 0x5d, 0xc1,
	0xd0, 0x9b, 0x9c, 0x9c, 0xd7, 0x79, 0x89, 0x67, 0x62, 0xa8, 0x05, 0xea, 0x16, 0x26, 0xe1, 0x8d,
	0x5a, 0xcd, 0x58, 0x34, 0x63, 0xc1, 0xab, 0x83, 0x70, 0x0a, 0xdd, 0xc2, 0xa4, 0x38, 0x91, 0xe3,
	0xb9, 0x64, 0xcb, 0x85, 0x2d, 0x12, 0xc2, 0x69, 0xb0, 0x2c, 0x8d, 0x7a, 0xf5, 0x5f, 0xdc, 0xfb,
	0xd4, 0xce, 0xe5, 0xc8, 0xe9, 0xd1, 0x20, 0xa4, 0x77, 0x0d, 0x10, 0x6e, 0x97, 0xd0, 0x55, 0xb0,
	0x2e, 0xe4, 0x13, 0x27, 0x7f, 0x0b, 0x93, 0xe3, 0xb3, 0x1e, 0x88, 0xf0, 0xb1, 0x68, 0xc6, 0x47,
	0xf8, 0x23, 0x11, 0xbf, 0xa3, 0x33, 0x9b, 0x42, 0xfb, 0xba, 0x22, 0x9c, 0xed, 0xbf, 0x40, 0x03,
	0x38, 0x92, 0x54, 0x7b, 0x1d, 0xcb, 0xa2, 0x3c, 0x91, 0xe9, 0x80, 0xc1, 0x8a, 0x97, 0x45, 0x41,
	0x8f, 0x6b, 0xbc, 0x08, 0x0b, 0xc4, 0xb5, 0x7a, 0x03, 0xb3, 0xa4, 0xce, 0xeb, 0x4c, 0x7b, 0xb3,
	0xa3, 0x58, 0x3e, 0x6e, 0xed, 0x28, 0xc5, 0xa7, 0xa2, 0x51, 0xed, 0xec, 0xbb, 0xa7, 0xf2, 0x87,
	0xa3, 0x94, 0xaf, 0x68, 0x65, 0x18, 0xae, 0x70, 0xcd, 0xb0, 0x09, 0xa8, 0xac, 0x4c, 0x42, 0xf8,
	0xac, 0x0d, 0xe8, 0x1b, 0x03, 0x0e, 0xd9, 0x25, 0xb6, 0xa2, 0xc3, 0xda, 0x3d, 0x17, 0x45, 0x24,
	0xf0, 0x68, 0x31, 0x33, 0xbb, 0x71, 0xf1, 0x3a, 0xb3, 0x36, 0xc7, 0xcb, 0x70, 0x06, 0x93, 0x7b,
	0x06, 0xbc, 0xf2, 0xce, 0x6b, 0x5f, 0x3b, 0xbc, 0x0a, 0x2b, 0x1f, 0xba, 0x7b, 0xf8, 0x39, 0xb8,
	0x7b, 0x1d, 0xfe, 0xb5, 0x75, 0x5f, 0x7e, 0xbd, 0xb7, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x1a,
	0x3e, 0x20, 0xd1, 0x8f, 0x03, 0x00, 0x00,
}
